enabled = "yes"

[settings]
url_prefix = "/conferences"
#subdomain = ""
#url_defaults = {}
#static_folder = "static"
template_folder = "templates"
#static_url_path = "/static/conferences"
#root_path = ""
#cli_group = ""

[session]
#conferences_session = "yes"
