version: "3.8"



services:
  app:
    container_name: traveller-lite
    build: .
    environment:
      IMP_CONFIG: docker.config.toml
      EMAIL_DEV_MODE: 0
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      EMAIL_SERVER: ${EMAIL_SERVER}
      EMAIL_PORT: ${EMAIL_PORT}
      SUPER_ADMIN_ACCOUNT: ${SUPER_ADMIN_ACCOUNT}
      SUPER_ADMIN_PASSWORD: ${SUPER_ADMIN_PASSWORD}

    restart: always

    ports:
      - "${FLASK_PORT}:5000"

    depends_on:
      - database


  database:
    container_name: traveller-lite-db
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-database:/var/lib/postgresql/data
    restart: always

    ports:
      - "5432:5432"


volumes:
  postgres-database:
