[lint]
ignore = ["F405", "F403"]

[tool.vite_transporter]
npm_exec = "npm"
npx_exec = "npx"
serve_app = "app"
vite_apps = ["vite_2024_frontend"]

[tool.pyqwe]
flask = "*:flask run --debug --host 127.0.0.1 --port 5001"
2024_update = "*(vite_2024_frontend):npm update"
2024_setup = "*(vite_2024_frontend):npm install"
2024_run = "*(vite_2024_frontend):npx vite --host 127.0.0.1 --port 5002"
