[lint]
ignore = ["F405", "F403"]

[tool.vite_transporter]
npm_exec = "npm"
npx_exec = "npx"
serve_app = "app"
vite_apps = ["vite_2024_frontend"]

[tool.pyqwe]
2024_update = "*(vite_2024_frontend):npm update"
2024_setup = "*(vite_2024_frontend):npm install"
2024_run = "*(vite_2024_frontend):npx vite"
