[lint]
ignore = ["F405", "F403"]

[tool.vtf]
npx_exec = "npx"
flask_app_dir = "app"
vite_app_dirs = ["vite_2024_frontend"]

[tool.pyqwe]
2024_update = "*(vite_2024_frontend):npm update"
2024_setup = "*(vite_2024_frontend):npm install"
2024_run = "*(vite_2024_frontend):npx vite"
