enabled = "yes"

[settings]
url_prefix = "/staff-only"
#subdomain = ""
#url_defaults = {}
#static_folder = "static"
#template_folder = "templates"
#static_url_path = "/static/staff"
#root_path = ""
#cli_group = ""

[session]
year = 0
