enabled = "yes"

[settings]
url_prefix = "/"
#subdomain = ""
#url_defaults = {}
#static_folder = "static"
template_folder = "templates"
static_url_path = "/static/auth"
#root_path = ""
#cli_group = ""

[session]
#auth_session = "yes"
