enabled = "yes"

[settings]
url_prefix = "/2023"
#subdomain = ""
#url_defaults = {}
static_folder = "static"
template_folder = "templates"
#static_url_path = "/static/2023"
#root_path = ""
#cli_group = ""

[session]
#2023_session = "yes"
